apiVersion: v1
kind: Service
metadata:
  name: mec-iperf3-svc
spec:
  selector:
    app: mec-app
  type: NodePort
  ports:
    # - name: sctp
    #   protocol: SCTP
    #   port: 38412
    - name: iperf3
      protocol: TCP
      port: 5201
      targetPort: 5201
